development:
  adapter: mysql2
  database: pattern_dev
  username: root
  password:
  charset: utf8
  collation: utf8_unicode_ci

test:
  adapter: mysql2
  database: pattern_test
  username: root
  password:
  charset: utf8
  collation: utf8_unicode_ci

production:
  adapter: mysql2
  database: pattern_prod
  username: root
  password:
  charset: utf8
  collation: utf8_unicode_ci